name: push-latest

# trigger on push to master
# only on Dockerfile related modifications
on:
  push:
    branches:
      - "**"
      - "!master"
    paths:
      - "Dockerfile"
      - "hashicorp.asc"
      - "tests/**"
      - ".dockerignore"
      - ".github/workflows/push-latest.yml"

env:
  IMAGE_NAME: "stroem/terraform-azure-cli"
  IMAGE_TAG: "latest"

jobs:
  build_push_latest:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Retrieve latest suported versions
        run: |
          TF_VERSION=$(make terraform-releases | jq -rR '[inputs] | .[0]')
          echo "TERRAFORM_VERSION=$TF_VERSION" >> $GITHUB_ENV

          AZ_VERSION=$(make azure-cli-releases | jq -rR '[inputs] | .[0]')
          echo "AZURE_CLI_VERSION=$AZ_VERSION" >> $GITHUB_ENV

      - name: Build image
        run: make build

      - name: Login to Docker Hub registry
        run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to registry
        run: make publish

      - name: Save image
        run: make artifact-save

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}
          path: build/image_${{ env.IMAGE_TAG }}.tar
