name: release

# trigger on published release
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
      - "!master"
  release:
    types: [published]

jobs:
  load_supported_versions:
    runs-on: ubuntu-20.04

    outputs:
      matrix: ${{ steps.set-versions.outputs.matrix }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Save released versions as output
        id: set-versions
        run: |
          VERSIONS=$(make releases | jq -c)
          echo ${VERSIONS}
          echo "::set-output name=versions::${VERSIONS}"

  build_push_release:
    runs-on: ubuntu-20.04
    needs:
      - load_supported_versions

    strategy:
      matrix: ${{ fromJSON(needs.load_supported_versions.outputs.matrix) }}

    env:
      IMAGE_NAME: "stroem/terraform-azure-cli"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          echo "IMAGE_TAG=terraform-${{ matrix.terraform }}_azurecli-${{ matrix.azurecli }}"
          echo "IMAGE_TAG=terraform-${{ matrix.terraform }}_azurecli-${{ matrix.azurecli }}" >> $GITHUB_ENV
          echo "TERRAFORM_VERSION=${{ matrix.terraform }}" >> $GITHUB_ENV
          echo "AZURE_CLI_VERSION=${{ matrix.azurecli }}" >> $GITHUB_ENV

      - name: Build image
        run: make build

      - name: Login to Docker Hub registry
        run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image to registry
        run: make publish

      - name: Save image
        run: make artifact-save

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_TAG }}
          path: build/image_${{ env.IMAGE_TAG }}.tar
